FROM node:latest

# RUN mkdir /app && \
#     chown -R root:root /app && \
#     chmod -R 755 /app
# COPY ./* /app/
# RUN cd /app && \
#     chmod +x /app/src


WORKDIR /gs-frontend

CMD tail -f /dev/null
# RUN npm install 

# CMD bash ./build.sh